### ISSUE TITLE
SPIFFS can eventually be removed

### ISSUE THREAD

**Issue by tobozo** [captFuture/M5Stack---LedMask#2]
Hey ^^ I can't really test your app as I'm missing the mask and the led strip, but while adding the sd-updater layer I found a possible optimization where you can get rid of the SPIFFS requirement by serializing the jpg data into the sketch and calling `M5.Lcd.drawJpg()` instead of `M5.Lcd.drawJpgFile()`.

I can submit a PR if you're interested, otherwise the changes are as described in the "pre-hook" section of this post https://github.com/tobozo/M5Stack-SD-Updater/issues/81#issuecomment-537485468

**Comment by tobozo** [comment]
also welcome to the [registry](https://phpsecu.re/m5stack/register?unstable) ^^

![image](https://user-images.githubusercontent.com/1893754/66056726-c6b74a00-e561-11e9-98df-724dffead981.png)

**Comment by captFuture** [comment]
:D thanks for adding - i was not aware that people noticed my project ^^ 
I changed the image from spiffs to byte array
